version: '3.8'


services:
  gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
    ports:
      - "80:80"
    environment:
      - REDIS_URL=${REDIS_URL}
      - JWT_ISS=${JWT_ISS}
      - JWT_AUD=${JWT_AUD}
    volumes:
      - ${PUBLIC_KEY_PATH}:/app/keys/public.pem:ro
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    depends_on:
      - redis
      - twivo-app
    networks:
      - twivo-network

  redis:
    image: redis:7-alpine
    container_name: twivo-media-redis
    restart: unless-stopped
    command: >
      redis-server 
      --appendonly no 
      --save "" 
      --tcp-keepalive 60
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - twivo-network

  weed-master:
    image: chrislusf/seaweedfs:latest
    container_name: twivo-weed-master
    restart: unless-stopped
    command: master -ip=weed-master
    ports:
      - "9333:9333"
    volumes:
      - seaweed-master-data:/data
    networks:
      - twivo-network

  weed-volume:
    image: chrislusf/seaweedfs:latest
    container_name: twivo-weed-volume
    restart: unless-stopped
    command: volume -mserver=weed-master:9333 -port=8085 -max=100 -dir=/data
    ports:
      - "8085:8085"
    volumes:
      - seaweed-volume-data:/data
    depends_on:
      - weed-master
    networks:
      - twivo-network

  weed-filer:
    image: chrislusf/seaweedfs:latest
    container_name: twivo-weed-filer
    restart: unless-stopped
    command: filer -master=weed-master:9333
    ports:
      - "8888:8888"
    volumes:
      - seaweed-filer-data:/data
    depends_on:
      - weed-master
      - weed-volume
    networks:
      - twivo-network
  
  twivo-app:
    build:
      context: .
      target: dev
    container_name: twivo-app
    restart: unless-stopped
    volumes:
      - .:/app
      - ${PUBLIC_KEY_PATH}:/app/keys/public.pem:ro
    environment:
      - REDIS_URL=${REDIS_URL}
      - SSL_CERT_PATH=/app/keys/public.pem
      - SEAWEEDFS_FILER_URL=${SEAWEEDFS_FILER_URL}
    networks:
      - twivo-network
    depends_on:
      redis:
        condition: service_healthy
      weed-filer:
        condition: service_started
    expose:
      - "8020"
  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    container_name: imgproxy
    restart: always
    ports:
      - "8000:8080"
    environment:
      IMGPROXY_INSECURE: "true"
      IMGPROXY_ENABLE_WEBP_DETECTION: "true"
      IMGPROXY_TTL: "2592000"
      IMGPROXY_MAX_SRC_FILE_SIZE: "15728640"
      IMGPROXY_IGNORE_SIGNATURE_ERRORS: "true"
    networks:
      - twivo-network

volumes:
  seaweed-master-data:
  seaweed-volume-data:
  seaweed-filer-data:

networks:
  twivo-network:
    driver: bridge